=== Gendalfion/JavaExamples/src/java_api_testing/xml/from_book/ch24/zooinventory.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="https://www.zooinventory.com"
	xmlns="https://www.zooinventory.com"
	elementFormDefault="qualified">
	<!-- Документ W3C XML Schema может использоваться для описания грамматики
	     XML-документов вместо устаревающей схемы DTD.
	     XML Schema - это обычный XML файл (обычно имеющий расширение .xsd),
	     использующий теги из пространства имен W3C XML Schema.
	     
	     Пример описываемого в данной схеме файла: zooinventory.xml
	     Пример включения схемы в XML-файл: zooinventory_XSD.xml -->

	<xs:element name="inventory">
	  <xs:complexType>
	    <xs:sequence>
	       <xs:element maxOccurs="unbounded" ref="animal"/>
	    </xs:sequence>
	  </xs:complexType>
	</xs:element>
	
	<xs:element name="name" type="xs:string"/>
	
	<xs:element name="animal">
	  <xs:complexType>
	    <xs:sequence>
	      <xs:element ref="name"/>
	      <xs:element name="species" type="xs:string"/>
	      <xs:element name="habitat" type="xs:string"/>
	      <xs:choice>
	         <xs:element name="food" type="xs:string"/>
	         <xs:element ref="foodRecipe"/>
		  </xs:choice>
	      <xs:element name="temperament" type="xs:string"/>
	      <xs:element name="weight" type="xs:double"/>
	    </xs:sequence>
	    <xs:attribute name="animalClass" default="unknown">
	      <xs:simpleType>
	        <xs:restriction base="xs:token">
	          <xs:enumeration value="unknown"/>
	          <xs:enumeration value="mammal"/>
	          <xs:enumeration value="reptile"/>
	          <xs:enumeration value="bird"/>
	        </xs:restriction>
	      </xs:simpleType>
	    </xs:attribute>
	  </xs:complexType>
	</xs:element>
	
	<xs:element name="foodRecipe">
	  <xs:complexType>
	    <xs:sequence>
	      <xs:element ref="name"/>
	      <xs:element maxOccurs="unbounded" name="ingredient" type="xs:string"/>
	    </xs:sequence>
	  </xs:complexType>
	</xs:element>

</xs:schema>

=== Gendalfion/JavaExamples/src/java_api_testing/xml/from_book/ch24/zooinventory_XSD.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- We define validation rules by W3C XML Schema validation (see zooinventory.xsd): -->
<inventory
	xmlns="https://www.zooinventory.com"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://www.zooinventory.com zooinventory.xsd">

	<animal animalClass="mammal">
        <name>Song Fang</name>
        <species>Giant Panda</species>
        <habitat>China</habitat> 
        <food>Bamboo</food>
        <temperament>Friendly</temperament>
        <weight>33.0</weight>
    </animal>
    
    <animal animalClass="mammal">
        <name>Cocoa</name>
        <species>Gorilla</species>
        <habitat>Central Africa</habitat>
        <foodRecipe>
            <name>Gorilla Chow</name>
            <ingredient>fruit</ingredient>
            <ingredient>shoots</ingredient>
            <ingredient>leaves</ingredient>
        </foodRecipe>
        <temperament>Know-it-all</temperament>
        <weight>45.0</weight>
    </animal>
    
</inventory>
